version: '3.0'
services:
  couchbase:
    image: couchbase/server:enterprise-7.0.0
    ports:
      - 8091-8096:8091-8096
      - 11210-11211:11210-11211
    networks:
      - my_network

networks:
  my_network: