version: '3.0'
services:
  couchbase:
    image: couchbase/server:enterprise-7.0.0
    ports:
      - 8091-8096:8091-8096
      - 11210-11211:11210-11211
    networks:
      - my_network
  mysql:
    image: mysql:latest
    hostname: mysql
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpswd
      MYSQL_DATABASE: warehouse
      MYSQL_USER: whuser
      MYSQL_PASSWORD: whpswd
    networks:
      my_network:
        aliases:
          - mysql.db.internal
    tty: true

networks:
  my_network: