version: '3.2'
services:
  gateway:
    image: edu.dubenco.alina/gateway:latest
    container_name: gateway
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Xms75M -Xmx100M"
      SERVER_PORT: 8080
    networks:
      - my_network

  service1:
    image: edu.dubenco.alina/service1:latest
    container_name: service1
    ports:
      - 8081:8080
    environment:
      JAVA_OPTS: "-Xms75M -Xmx100M"
      SERVER_PORT: 8080
      SERVICE_URL: http://service1:8080/
      GATEWAY_URI: http://gateway:8080/gateway/services
    depends_on:
      - gateway
    networks:
      - my_network

  service2:
    image: edu.dubenco.alina/service2:latest
    container_name: service2
    ports:
      - 8082:8080
    environment:
      JAVA_OPTS: "-Xms75M -Xmx100M"
      SERVER_PORT: 8080
      SERVICE_URL: http://service2:8080/
      GATEWAY_URI: http://gateway:8080/gateway/services
    depends_on:
      - gateway
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
